import "./globals.css";

export const metadata = {
  title: "Dev-TzHasan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-primary " >
        {children}
      </body>
    </html>
  );
}
