import "./globals.css";
import AuthProvider from "./provider/authProvider";
import MenubarProvider from "./provider/menubarProvider";
import ThemeProvider from "./provider/themeProvider";

export const metadata = {
  title: "Dev-TzHasan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-primary ">
        <AuthProvider>
          <MenubarProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </MenubarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
